version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - medpark
    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - 6379:6379
    networks:
      - medpark

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
    networks:
      - medpark
      
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - medpark
    volumes:
      - mongo:/data/db
  
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5340:80
    networks:
      - medpark
    volumes: 
      - seq:/data
      
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - medpark
    volumes:
      - consul:/consul/data

networks:
  medpark:
    name: medpark-network

volumes:
  rabbitmq:
    driver: local
  mongo:
    driver: local
  seq:
    driver: local
  consul:
    driver: local